<?php

/**
 * @file
 * The SSO Module File.
 */

use Drupal\Core\Url;

/**
 * Implements hook_page_attachments().
 */
function lr_sso_page_attachments(&$page) {
  global $user;
  $sso_config = \Drupal::config('lr_sso.settings');
  $sl_config = \Drupal::config('lr_ciam.settings');
  $site_name = $sl_config->get('sso_site_name');

  if ($sso_config->get('sso_enable') == 1 && !empty($site_name)) {
    $user = \Drupal::currentUser()->getRoles();
    $my_settings['logoutUrl'] = Url::fromRoute('user.logout')->setAbsolute()->toString();

    if (\Drupal::currentUser()->isAnonymous()) {

      $my_settings['isNotLogin'] = TRUE;
      $my_settings['loginUrl'] = Url::fromRoute('user.login')->setAbsolute()->toString();
    }
    if (!\Drupal::currentUser()->isAnonymous() && !in_array("administrator", $user)) {

      $my_settings['isNotLoginThenLogout'] = TRUE;
    }

    $page['#cache']['contexts'][] = 'user.roles';
    $page['#attached']['drupalSettings']['sso'] = $my_settings;
    $page['#attached']['library'][] = 'lr_sso/drupal.coresso';
  }
}
