<?php

use Drupal\Core\Url;
use Drupal\Core\Form\FormStateInterface;


/**
 * Add required sso js files to page.
 *
 * @param $vars
 * @param $hook
 */
function lr_sso_page_attachments(&$page) {
  $sso_config = \Drupal::config('lr_sso.settings');
  $sl_config = \Drupal::config('lr_ciam.settings');
  $site_name = $sl_config->get('sso_site_name');

  if ($sso_config->get('sso_enable') == 1 && !empty($site_name)) {
    $my_settings['frontUrl'] = Url::fromRoute('<front>')->setAbsolute()->toString();   
     
      if ( \Drupal::currentUser()->isAnonymous()) {
          
            $my_settings['isNotLogin'] = true;
            $my_settings['loginUrl'] = Url::fromRoute('user.login')->setAbsolute()->toString(); 
      }     
      if (  !\Drupal::currentUser()->isAnonymous()) {
          
            $my_settings['isNotLoginThenLogout'] = true;
            $my_settings['logoutUrl'] = Url::fromRoute('user.logout')->setAbsolute()->toString(); 
      }  
      
    $page['#cache']['contexts'][] = 'user.roles';
    $page['#attached']['drupalSettings']['sso']  = $my_settings;
    $page['#attached']['library'][] = 'lr_sso/drupal.coresso';   
  }
}