<?php

/**
 * @file
 * Provides uninstall function for the CIAM module.
 */

/**
 * Implements hook_uninstall().
 */
function lr_identity_experience_framework_uninstall() {
  variable_del('lr_ief_enable');
  variable_del('lr_ief_logout');
}

/**
 * Implements hook_schema().
 */
function lr_identity_experience_framework_schema() {
  db_update('system')
    ->fields(array('weight' => 5))
    ->condition('name', 'lr_identity_experience_framework', '=')
    ->execute();
}
