<?php

/**
 * @file
 * Enables the use of personal and site-wide contact forms.
 */
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Entity\EntityTypeInterface;
use \LoginRadiusSDK\Utility\Functions;
use \LoginRadiusSDK\LoginRadiusException;
use \LoginRadiusSDK\Clients\IHttpClient;
use \LoginRadiusSDK\Clients\DefaultHttpClient;
use \LoginRadiusSDK\Utility\SOTT;
use \LoginRadiusSDK\CustomerRegistration\Social\SocialLoginAPI;
use \LoginRadiusSDK\CustomerRegistration\Authentication\UserAPI;
use \LoginRadiusSDK\CustomerRegistration\Management\AccountAPI;

module_load_include('php', 'lr_ciam', 'customhttpclient');
global $apiClient_class;
$apiClient_class = 'CustomHttpClient';

/**
 * Implements hook_theme().
 *
 * @return array
 */
function lr_ciam_theme() {
    $path = drupal_get_path('module', 'lr_ciam') . '/theme';
    $theme = array(
      'user_login_form' => array(
        'template' => 'user_login_form',
        'render element' => 'form',
        'path' => $path,
      ),
      'change_password' => array(
        'variables' => array(
          'params' => NULL,
        ),
        'template' => 'change_password',
        'path' => $path,
      ),
      '2fa_container' => array(
        'variables' => array(
          'params' => NULL,
        ),
        'template' => '2fa_container',
        'path' => $path,
      ),
      'lr_update_phone' => array(
        'variables' => array(
          'params' => NULL,
        ),
        'template' => 'lr_update_phone',
        'path' => $path,
      ),
      'lr_backup_codes' => array(
        'variables' => array(
          'params' => NULL,
        ),
        'template' => 'lr_backup_codes',
        'path' => $path,
      ),
      'remove_email' => array(
        'variables' => array(
          'params' => NULL,
        ),
        'template' => 'remove_email',
        'path' => $path,
      ),
      'add_email' => array(
        'variables' => array(
          'params' => NULL,
        ),
        'template' => 'add_email',
        'path' => $path,
      ),
      'user_pass' => array(
        'template' => 'user_pass',
        'render element' => 'form',
        'path' => $path,
      ),
      'ciam_social_widget_container' => array(
        'variables' => array(
          'params' => NULL,
        ),
        'template' => 'ciam_social_widget_container',
        'path' => $path,
      ),
      'lr_ciam_linked' => array(
        'variables' => array(
          'params' => NULL,
        ),
        'template' => 'lr_ciam_linked',
        'path' => $path,
      ),
      'lr_ciam_popup' => array(
        'variables' => array(
          'params' => NULL,
        ),
        'template' => 'lr_ciam_popup',
        'path' => $path,
      ),
      'lr_loading' => array(
        'template' => 'lr_loading',
        'variables' => array(
          'params' => NULL,
        ),
        'path' => $path,
      ),
      'lr_message' => array(
        'template' => 'lr_message',
        'variables' => array(
          'params' => NULL,
        ),
        'path' => $path,
      ),
    );

    $theme['user_register_form'] = array(
      'template' => 'user_register_form',
      'render element' => 'form',
      'path' => $path,
    );
    return $theme;
}

/**
 * Added Required variable to use in template fie.
 *
 * @param $vars
 */
function template_preprocess_lr_ciam_linked(&$vars) {
    global $base_url;
    $vars['currentid'] = $_SESSION['_sf2_attributes']['lrID'];
    $vars['currentprovider'] = $_SESSION['current_provider'];
    $vars['image_url'] = $base_url . '/' . drupal_get_path('module', 'lr_ciam') . '/images';
    $vars['callback'] = lr_ciam_get_callback_url();
}

/**
 * Show and hide user pass form.
 *
 * @param $variables
 */
function template_preprocess_user_pass(&$variables) {
    $config = \Drupal::config('ciam.settings');
    $variables['api_key'] = trim($config->get('api_key'));
    if (!\Drupal::currentUser()->isAnonymous()) {
        $variables['showpassonlogin'] = false;
        $variables['rendered'] = drupal_render_children($variables['form']);
    }
    else {
        $variables['showpassonlogin'] = true;
    }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @param $form
 * @param $form_state
 * 
 * return $form
 */
function lr_ciam_form_user_pass_alter(&$form, FormStateInterface $form_state) {
    if (!\Drupal::currentUser()->isAnonymous()) {
        $user = \Drupal::currentUser();
        $form['name']['#type'] = 'value';
        $form['name']['#value'] = $user->getEmail();
        $form['mail'] = array(
          '#prefix' => '<p>',
          '#markup' => t('Password reset instructions will be mailed to %email. You must log out to use the password reset link in the email.', array('%email' => $user->getEmail())),
          '#suffix' => '</p>',
        );

        $form['actions'] = array('#type' => 'actions');
        $form['actions']['submit'] = array('#type' => 'submit', '#value' => t('Submit'));
        $form['#cache']['contexts'][] = 'url.query_args';
        return $form;
    }
}

/**
 * Add variable to register form.
 *
 * @param $variables
 * 
 */
function template_preprocess_user_register_form(&$variables) {
    $variables['admin_access'] = true;
    $user = \Drupal::currentUser()->getRoles();
    if (in_array("administrator", $user)) {
        $variables['admin_access'] = false;
    }
    $config = \Drupal::config('ciam.settings');
    $variables['interface_label'] = $config->get('interface_label');
    $variables['api_key'] = trim($config->get('api_key'));
    $variables['rendered'] = drupal_render_children($variables['form']);
}

/**
 * Get pop up title.
 *
 * @param $variables
 * 
 */
function template_preprocess_lr_ciam_popup(&$variables) {
    $config = \Drupal::config('ciam.settings');
    $variables['popup_title'] = $config->get('popup_title');
}

/**
 * Implements hook_preprocess().
 *
 * @param $variables
 * 
 */
function lr_ciam_preprocess(&$variables) {  
    $variables['image_path'] = $GLOBALS['base_url'] . '/' . drupal_get_path('module', 'lr_ciam') . '/images/loading.gif';
}

/**
 * Add variable to user login form.
 *
 * @param $variables
 * 
 */
function template_preprocess_user_login_form(&$variables) {
    $config = \Drupal::config('ciam.settings');
    $variables['interface_label'] = $config->get('interface_label');
    $variables['api_key'] = trim($config->get('api_key'));
}


/**
 * Get provider name.
 *
 * @param $userprofile
 * @param $token
 * 
 * return array
 */
function lr_ciam_add_loginradius_userdata($userprofile, $token) {
    $config = \Drupal::config('ciam.settings');
    $apiKey = trim($config->get('api_key'));
    $apiSecret = trim($config->get('api_secret'));

    $socialLoginObj = new SocialLoginAPI($apiKey, $apiSecret, array('output_format' => 'json'));
    try {
        $socialProfileData = $socialLoginObj->getUserProfiledata($token);
    }
    catch (LoginRadiusException $e) {
         \Drupal::logger('ciam')->error($e);
    }
    $_SESSION['current_provider'] = isset($socialProfileData->Provider) ? $socialProfileData->Provider : '';
    $_SESSION['provider'] = isset($userprofile->Provider) ? $userprofile->Provider : '';;
}


/**
 * Implements hook_page_attachment().
 *
 * @param $page
 */
function lr_ciam_page_attachments(&$page) {
    $config = \Drupal::config('ciam.settings');
    if (isset($_COOKIE['lr_message']) && $_COOKIE['lr_message'] != '') { 
        
        $sec = $config->get('ciam_auto_hide_messages');
        $message = isset($_COOKIE['lr_message']) ? $_COOKIE['lr_message'] : '';                       
        $response = (isset($_GET['lrresponse']) && $_GET['lrresponse'] != 'true') ? "error" : "success" ;
        setcookie("lr_message", "", time() - 3600, "/");
        if($message!= ""){
            if($response == 'error'){
                drupal_set_message($message, $response);
                if($sec != '' && $sec != '0'){
                    header("Refresh:$sec");
                }
            } else {
                drupal_set_message($message);   
                if($sec != '' && $sec != '0'){
                    header("Refresh:$sec");
                }
            }
        }                             
    }
    $user = \Drupal::currentUser();
    $emailVerificationUrl = Url::fromRoute('<front>')->setAbsolute()->toString();
    $forgotVerificationUrl = Url::fromRoute('user.login')->setAbsolute()->toString();

    $path = parse_url(Url::fromRoute('<front>')->toString());
    $sso_path = $path['path'];

    if (\Drupal::currentUser()->isAnonymous()) {
        $loggedIn = false;
    }
    else {
        $loggedIn = true;
    }
    $access_token = isset($_SESSION['access_token']) ? $_SESSION['access_token'] : '';
    $my_settings = array(
      'verificationUrl' => $emailVerificationUrl,
      'forgotPasswordUrl' => $forgotVerificationUrl,
      'loggedIn' => $loggedIn,
      'accessToken' => $access_token,
      'appName' => trim($config->get('sso_site_name')),
      'apiKey' => trim($config->get('api_key')),  
      'autoHideTime' => trim($config->get('ciam_auto_hide_messages')),     
      'appPath' => trim($sso_path),
      'callback' => urldecode(lr_ciam_get_callback_url()),
      'home' => Url::fromRoute('<front>')->setAbsolute()->toString()
    );

    if ($config->get('ciam_terms_and_condition_html') != '') {
        $my_settings['termsAndConditionHtml'] = $config->get('ciam_terms_and_condition_html');
    }

    if (is_numeric($config->get('ciam_form_render_delay')) != '0') {
        $my_settings['formRenderDelay'] = (int) $config->get('ciam_form_render_delay');
    }

    $min_length = $config->get('ciam_min_password_length');
    $max_length = $config->get('ciam_max_password_length');
    if (!empty($min_length)) {
        $my_settings['passwordminlength'] = $min_length;
    }
    if (!empty($max_length)) {
        $my_settings['passwordmaxlength'] = $max_length;
    }

    if ($config->get('ciam_inform_validation_messages') != '' && $config->get('ciam_inform_validation_messages') != 'false') {
        $my_settings['formValidationMessage'] = (boolean) $config->get('ciam_inform_validation_messages');
    }
    if ($config->get('ciam_welcome_email_template') != '') {
        $my_settings['welcomeEmailTemplate'] = $config->get('ciam_welcome_email_template');
    }
    if ($config->get('ciam_forgot_password_template') != '') {
        $my_settings['resetPasswordEmailTemplate'] = $config->get('ciam_forgot_password_template');
    }
    if ($config->get('ciam_email_verification_template') != '') {
        $my_settings['verificationEmailTemplate'] = $config->get('ciam_email_verification_template');
    }    
    if ($config->get('ciam_enable_remember_me') != '' && $config->get('ciam_enable_remember_me') != 'false') {
        $my_settings['stayLogin'] = (boolean) $config->get('ciam_enable_remember_me');
    }
    if ($config->get('ciam_ask_required_field_on_traditional_login') != '' && $config->get('ciam_ask_required_field_on_traditional_login') != 'false') {
        $my_settings['askRequiredFieldForTraditionalLogin'] = (boolean) $config->get('ciam_ask_required_field_on_traditional_login');
    }
    if ($config->get('ciam_display_password_strength') != '' && $config->get('ciam_display_password_strength') != 'false') {
        $my_settings['displayPasswordStrength'] = (boolean) $config->get('ciam_display_password_strength');
    }
    if ($config->get('ciam_enable_recaptcha') != '' && $config->get('ciam_enable_recaptcha') != 'false') {
        $my_settings['enableGoogleRecaptcha'] = true;
        $my_settings['recaptchaType'] = $config->get('ciam_v2_recaptcha_type');
        if ($config->get('ciam_v2_recaptcha_site_key') != '') {
            $my_settings['v2RecaptchaSiteKey'] = $config->get('ciam_v2_recaptcha_site_key');
        }
    } else {
          $my_settings['sott'] = lr_ciam_get_sott($config->get('api_key'), $config->get('api_secret'));
    }
    if ($config->get('ciam_debug_mode') != '' && $config->get('ciam_debug_mode') != 'false') {
        $my_settings['debugMode'] = (boolean) $config->get('ciam_debug_mode');
    }

    if ($config->get('ciam_login_type') != '' && $config->get('ciam_login_type') == 'email') {
        $emailVerifyOpt = $config->get('ciam_email_verification_condition');
        if (isset($emailVerifyOpt) && $emailVerifyOpt != '') {
            $my_settings['loginTypeEmail'] = true;
            if ($emailVerifyOpt == '0') {          
                if ($config->get('ciam_enable_login_on_email_verification') != '' && $config->get('ciam_enable_login_on_email_verification') != 'false') {
                    $my_settings['loginOnEmailVerification'] = (boolean) $config->get('ciam_enable_login_on_email_verification');
                } if ($config->get('ciam_prompt_password_on_social_login') != '' && $config->get('ciam_prompt_password_on_social_login') != 'false') {
                    $my_settings['promptPasswordOnSocialLogin'] = (boolean) $config->get('ciam_prompt_password_on_social_login');
                } if ($config->get('ciam_enable_user_name') != '' && $config->get('ciam_enable_user_name') != 'false') {
                    $my_settings['usernameLogin'] = (boolean) $config->get('ciam_enable_user_name');
                } if ($config->get('ciam_ask_email_always_for_unverified') != '' && $config->get('ciam_ask_email_always_for_unverified') != 'false') {
                    $my_settings['askEmailForUnverifiedProfileAlways'] = (boolean) $config->get('ciam_ask_email_always_for_unverified');
                }
            }
            elseif ($emailVerifyOpt == '1') {
                if ($config->get('ciam_enable_login_on_email_verification') != '' && $config->get('ciam_enable_login_on_email_verification') != 'false') {
                    $my_settings['loginOnEmailVerification'] = (boolean) $config->get('ciam_enable_login_on_email_verification');
                } if ($config->get('ciam_ask_email_always_for_unverified') != '' && $config->get('ciam_ask_email_always_for_unverified') != 'false') {
                    $my_settings['askEmailForUnverifiedProfileAlways'] = (boolean) $config->get('ciam_ask_email_always_for_unverified');
                }
                $my_settings['optionalEmailVerification'] = true;
            }
            elseif ($emailVerifyOpt == '2') {
                $my_settings['disabledEmailVerification'] = true;
            }
        }
    }

    if ($config->get('ciam_login_type') != '' && $config->get('ciam_login_type') == 'phone') {
        if ($config->get('ciam_enable_phone_login') != '' && $config->get('ciam_enable_phone_login') != 'false') {
            $my_settings['loginTypePhone'] = true;
            $my_settings['phoneLogin'] = true;
            if ($config->get('ciam_exist_phone_number') != '' && $config->get('ciam_exist_phone_number') != 'false') {
                $my_settings['existPhoneNumber'] = (boolean) $config->get('ciam_exist_phone_number');
            }            
            if ($config->get('ciam_sms_template') != '') {
                $my_settings['smsTemplateWelcome'] = $config->get('ciam_sms_template');
            }
            if ($config->get('ciam_sms_template_phone_verification') != '') {
                $my_settings['smsTemplatePhoneVerification'] = $config->get('ciam_sms_template_phone_verification');
            }
            if ($config->get('ciam_instant_otp_login') != '' && $config->get('ciam_instant_otp_login') != 'false') {
                $my_settings['instantOTPLogin'] = (boolean) $config->get('ciam_instant_otp_login');
            }
            if ($config->get('ciam_sms_template_one_time_passcode') != '') {
                $my_settings['smsTemplateInstantOTPLogin'] = $config->get('ciam_sms_template_one_time_passcode');
            }
            if ($config->get('ciam_instant_otp_login_button_label') != '') {
                $my_settings['instantOTPLoginButtonLabel'] = $config->get('ciam_instant_otp_login_button_label');
            }
        }
    }
    elseif ($config->get('ciam_instant_link_login') != '' && $config->get('ciam_instant_link_login') != 'false') {
        $my_settings['instantLinkLogin'] = (boolean) $config->get('ciam_instant_link_login');
        if ($config->get('ciam_instant_link_login_email_template') != '') {
            $my_settings['instantLinkLoginEmailTemplate'] = $config->get('ciam_instant_link_login_email_template');
        }
        if ($config->get('ciam_instant_link_login_button_label') != '') {
            $my_settings['instantLinkLoginButtonLabel'] = $config->get('ciam_instant_link_login_button_label');
        }
    }

    if ($config->get('ciam_enable_2fa') != '' && $config->get('ciam_enable_2fa') != 'false') {
        $my_settings['enableTwoFactorAuth'] = true;
        $my_settings['twoFactorAuthFlow'] = $config->get('ciam_2fa_flow');

        if ($config->get('ciam_google_authentication') != '' && $config->get('ciam_google_authentication') != 'false') {
            $my_settings['googleAuthentication'] = (boolean) $config->get('ciam_google_authentication');
        }
        if ($config->get('ciam_sms_template_2fa') != '') {
            $my_settings['smsTemplate2FA'] = $config->get('ciam_sms_template_2fa');
        }
    }

    if ($config->get('ciam_custom_options') != '') {
        $my_settings['customScript'] = "";
        $jsondata = lr_ciam_json_validate($config->get('ciam_custom_options'));
        if (is_object($jsondata)) {
            foreach ($jsondata as $key => $value) {
                $my_settings['customScript'] .= "commonOptions." . $key . "=";
                if (is_object($value) || is_array($value)) {
                    $encodedStr = json_encode($value);
                    $my_settings['customScript'] .= $encodedStr . ';';
                }
                else {
                    $my_settings['customScript'] .= '"' . $value . '"' . ';';
                }
            }
        }
        else {
            if (is_string($jsondata)) {
                $my_settings['customScript'] = $jsondata;
            }
        }
    }
    
    $page['#attached']['drupalSettings']['ciam'] = $my_settings;
    $page['#attached']['library'][] = 'lr_ciam/drupal.ciam_core';
    $page['#attached']['library'][] = 'lr_ciam/drupal.ciam_custom';
}

/**
 * Generate sott.
 *
 * @param $apikey 
 * @param $secret 
 * @return json|string
 */

function lr_ciam_get_sott($apiKey, $secret) {
    if ($apiKey != '' && $secret != '') {
        $accountObj = new AccountAPI($apiKey, $secret, array('output_format' => 'json'));
        try { 
            $result = $accountObj->generateSOTT('10');
            return $result = isset($result->Sott) ? $result->Sott : '';
        }
        catch (LoginRadiusException $e) {
             \Drupal::logger('ciam')->error($e);
        }    
    }
}

/**
 * Check String is json or not.
 *
 * @param $string 
 * @return json|string
 */
function lr_ciam_json_validate($string) {
    $result = json_decode(str_replace("'", '"', $string));
    if (json_last_error() == JSON_ERROR_NONE) {
        return $result;
    }
    else {
        return $string;
    }
}

/**
 * hook_mail.
 *
 * @param $key
 * @param $message 
 * @param $params 
 * @return json|string
 */
function lr_ciam_mail($key, &$message, $params) {
    $data['user'] = $params['account'];
    $options['langcode'] = $message['langcode'];
    user_mail_tokens($variables, $data, $options);
    switch ($key) {
        case 'welcome_email':
            $message['subject'] = t('Thank you for registering at @site', $variables, $options);
            $message['body'][] = t("Thank you for registering at @site.

You will be able to login in the future using

Username : @username
Password : @pass

--  [site:name] team", $variables, $options);
            break;
    }
}

/**
 * Get Callback Url For Social Login Interface.
 *
 * @return string
 */
function lr_ciam_get_callback_url() {
    global $base_url;
    $destination = (\Drupal::destination()->getAsArray());
    $callback = $destination['destination'];

    if (strpos($callback, 'ajax') !== FALSE) {
        if (isset($_SESSION['redirect_url'])) {
            return $_SESSION['redirect_url'];
        }
        else {
            $callback = Url::fromRoute('user');
        }
    }


    $url = Url::fromUserInput('/user/ciamlogin', array(
          'query' => array('destination' => $callback),
          'absolute' => TRUE,
        ))->toString();

    $request_uri = \Drupal::request()->getRequestUri();
    if (strpos($request_uri, 'redirect_to') !== FALSE) {
        $vid = \Drupal::request()->query->get('redirect_to');
        $url .= "&redirect_to=" . urldecode($vid);
    }
    $parseURL = parse_url($base_url);
    $HTTP_REFERER = isset($_SERVER["HTTP_REFERER"]) ? $_SERVER["HTTP_REFERER"] : '';
    if (isset($parseURL['host']) && !empty($parseURL['host']) && (strpos($HTTP_REFERER, $parseURL['host']) !== false)) {
        $_SESSION['referer_url'] = $_SERVER["HTTP_REFERER"];
    }
    return urlencode($url);
}

/**
 * Update user data after save.
 * 
 * @param $user
 * @param $userprofile
 */
function lr_ciam_add_user_data_after_save($user, $userprofile) {
    $user_manager = \Drupal::service('lr_ciam.user_manager');
    $user_manager->lr_ciam_update_user_table($userprofile->Uid, $user->id());
}

/**
 * 
 * Implements hook_user_insert().
 * 
 * @param $account
 * 
 */
function lr_ciam_user_insert($account) {
    
    $user = \Drupal::currentUser()->getRoles();
    if (in_array("administrator", $user)) {

        if (isset($_POST['op']) && $_POST['op'] == 'Create new account') {
            $user_manager = \Drupal::service('lr_ciam.user_manager');
            $params = '{
            "Email":[
               {
                  "Type":"Primary",
                  "Value":"'.$_POST['mail'].'"
               }
            ],
            "UserName":"'.$_POST['name'].'",
            "Password":"'.$_POST['pass']['pass1'].'"
            }';   

            $response = $user_manager->lr_ciam_create_user($params);
            if (isset($response->Uid) && !empty($response->Uid)) {
                
                \Drupal\Core\Database\Database::getConnection()->update('users_field_data')
                    ->fields(array(
                      'login' => REQUEST_TIME,
                    ))
                    ->condition('uid', $account->id())
                    ->execute();
                $user_manager->lr_ciam_update_user_table($response->Uid, $account->id());

                if (isset($_POST['notify']) && $_POST['notify'] == '1') {
                    try {
                        $forgotVerificationUrl = Url::fromRoute('user.login')->setAbsolute()->toString(); 
                        $result = $user_manager->lr_ciam_forgot_password(trim($_POST['mail']), $forgotVerificationUrl);                        
      
                        if (isset($result->IsPosted) && $result->IsPosted) {
                            drupal_set_message(t('A welcome message with further instructions has been emailed to the new user <a href=":url">%name</a>.', array(':url' => $account->url(), '%name' => $_POST['name'])));
                        }
                    }
                    catch (LoginRadiusException $e) {
                        $msg = isset($e->getErrorResponse()->description) ? $e->getErrorResponse()->description : 'error';
                        drupal_set_message(t($msg), 'error');
                        $response = new RedirectResponse(Url::fromRoute('<current>')->toString());
                        $response->send();
                        exit();
                    }
                }
                if (isset($_POST['status']) && $_POST['status'] == "0") {
                    $user_manager->lr_ciam_block_user($response->Uid);
                }
            }
        }
    }
}

/**
 * Implements hook_user_presave().
 * 
 * @param $account
 * 
 */

function lr_ciam_user_presave($account) {
    $user_manager = \Drupal::service('lr_ciam.user_manager');
    $ciam_uid = $user_manager->lr_ciam_get_ciam_uid($account->id());
    $ciam_uname = $user_manager->lr_ciam_get_ciam_uname($account->id());
    $config = \Drupal::config('ciam.settings');
    $apiKey = trim($config->get('api_key'));
    $apiSecret = trim($config->get('api_secret'));    

        if (isset($_POST['op']) && $_POST['op'] == 'Save') {
            if (isset($_POST['form_id']) && $_POST['form_id'] == 'user_form') {
                if (isset($_POST['name']) && $_POST['name'] != '') {

                    if ($ciam_uname != $_POST['name']) {

                        $params = '{            
                          "UserName":"' . $_POST['name'] . '"          
                          }';
                        try {
                            $accountObject = new AccountAPI($apiKey, $apiSecret, array('output_format' => 'json'));
                            $accountObject->update($ciam_uid, $params);
                        }
                        catch (LoginRadiusException $e) {                           
                            $msg = isset($e->getErrorResponse()->description) ? $e->getErrorResponse()->description : 'error';
                            $response = new RedirectResponse(Url::fromRoute('<current>')->toString());
                            $response->send();
                            exit();
                        }
                    }
                }
            }
        }    
}

/**
 * Implements hook_user_update().
 * 
 * @param $account
 * 
 */
function lr_ciam_user_update($account) {
    
    $config = \Drupal::config('ciam.settings');
    $apiKey = trim($config->get('api_key'));
    $apiSecret = trim($config->get('api_secret'));
    $user_manager = \Drupal::service('lr_ciam.user_manager');
    $ciam_uid = $user_manager->lr_ciam_get_ciam_uid($account->id());
    $field_defaults = $config->get('user_fields', array());
    if (isset($_POST['op']) && $_POST['op'] == 'Save') { 
    $output = array();
      foreach($field_defaults as $key=>$value) {
          if($value=='BirthDate'){             
              $output[$value] = isset($_POST[$key][0]["value"]['date']) ? $_POST[$key][0]["value"]['date'] : '';
              $sldate = explode('-', $output[$value]);            
                $year = isset($sldate[0]) ? trim($sldate[0]) : '';
                $month = isset($sldate[1]) ? trim($sldate[1]) : '';
                $date = isset($sldate[2]) ? trim($sldate[2]) : '';
                $formatDate = trim($month . '-' . $date . '-' . $year);
                $output[$value] = $formatDate;               
             } else {
              $output[$value] = isset($_POST[$key][0]["value"]) ? $_POST[$key][0]["value"] : '';
          } 
      }

        try {       
            $accountObject = new AccountAPI($apiKey, $apiSecret, array('output_format' => 'json'));
            $result =  $accountObject->update($ciam_uid, $output);
        }
        catch (LoginRadiusException $e) {                           

        }     
     

    if (isset($_POST['status'])) {
      if ($_POST['status'] == "0" && isset($ciam_uid) && !empty($ciam_uid)) {       
          $user_manager->lr_ciam_block_user($ciam_uid);
      }
      else {         
          $user_manager->lr_ciam_unblock_user($ciam_uid);
      }
    }
    if (isset($_POST['pass']['pass1']) && !empty($_POST['pass']['pass1'])) {       
    $user = \Drupal::currentUser()->getRoles();
      if (in_array("administrator", $user)) {       
          if (empty($ciam_uid)) {           
            $params = '{
            "Email":[
               {
                  "Type":"Primary",
                  "Value":"'.$account->getEmail().'"
               }
            ],
            "UserName":"'.$account->getUsername().'",
            "Password":"'.$_POST['pass']['pass1'].'"
            }';  
            $user_manager->lr_ciam_create_user($params);
            return;
          } 
        else {
          $user_manager->lr_ciam_set_password($ciam_uid, $_POST['pass']['pass1']);
        }
      }
    }
  } elseif (isset($_POST['op']) && $_POST['op'] == 'Apply' && isset($ciam_uid) && !empty($ciam_uid)) {   
       
      if (isset($_POST['action']) && $_POST['action'] == 'user_block_user_action') {
            $user_manager->lr_ciam_block_user($ciam_uid);
        }
        elseif (isset($_POST['action']) && $_POST['action'] == 'user_unblock_user_action') {
            $user_manager->lr_ciam_unblock_user($ciam_uid);
        }   
    }   
}

/**
 * User form alter.
 * 
 * @param $form
 * @param $form_state
 */
function lr_ciam_form_user_form_alter(&$form, FormStateInterface $form_state) {
    $user_manager = \Drupal::service('lr_ciam.user_manager');
    $config = \Drupal::config('ciam.settings');
    $user = \Drupal::currentUser()->getRoles();

    if (!in_array("administrator", $user) && !\Drupal::currentUser()
            ->isAnonymous()) {

        unset($form['#validate'][1]);
        unset($form['account']['pass']);
        unset($form['account']['current_pass']);
       // $form['account']['mail']['#disabled'] = TRUE;
        $apiKey = trim($config->get('api_key'));
        $apiSecret = trim($config->get('api_secret'));
        $userObject = new UserAPI($apiKey, $apiSecret, array('output_format' => 'json'));
        try {
            $userprofile = $userObject->getProfile($_SESSION['access_token']);
        }
        catch (LoginRadiusException $e) {
            \Drupal::logger('ciam')->error($e);
        }

        $defaultEmail = isset($userprofile->Email) ? $userprofile->Email[0]->Value : '';
        
        if(isset($defaultEmail) && $defaultEmail != ''){
        if ($form['account']['mail']['#default_value'] != $defaultEmail) {
               \Drupal::database()->update('users_field_data')
                ->condition('mail', $form['account']['mail']['#default_value'])
                ->fields(['mail' => $defaultEmail])
                ->execute();
        }}

        if ($config->get('ciam_login_type') == 'phone') {
            if ($config->get('ciam_enable_phone_login') == 'true') {
                $form['lr_update_phone'] = array(
                  '#type' => 'item',
                  '#theme' => 'lr_update_phone',
                  '#attributes' => array('class' => array('lr-phone-container')),
                  '#weight' => -15,
                  '#open' => TRUE,
                );
            }
        }
        elseif ($config->get('ciam_login_type') == 'email') {
            $form['account']['emailSetting'] = array(
              '#type' => 'fieldset',
              '#title' => t('Email Settings'),
              '#collapsible' => TRUE,
              '#collapsed' => TRUE,
            );

            $header = array(
              'email' => array('data' => 'Email'),
              'action' => array('data' => 'Action')
            );

            $form['account']['emailSetting']['add'] = array(
              '#type' => 'item',
              '#markup' => '<div class="addEmail" id="addEmail">Add Email</div>',
            );
            $emailCount = isset($userprofile->Email) ? count($userprofile->Email) : '0';
            if ($emailCount > 0) {
                for ($i = 0; $i < $emailCount; $i++) {
                    $email[$i] = array(
                      '#type' => 'email',
                      '#attributes' => array('readonly' => 'readonly'),
                      '#default_value' => ($userprofile->Email[$i]->Value ? $userprofile->Email[$i]->Value : '')
                    );

                    $action[$i] = array(
                      '#type' => 'item',
                      '#markup' => '<div class="removeEmail" id="removeEmail_' . $i . '">Remove</div>',
                    );

                    $rows['customize_field_' . $i] = array(
                      'data' => array(
                        'field' => array('data' => &$email[$i]),
                        'label' => array('data' => &$action[$i])
                      )
                    );

                    $data_to_send['customize_field_' . $i] = array(
                      'field' => &$email[$i],
                      'label' => &$action[$i]
                    );
                }

                $form['account']['emailSetting']['table'] = array(
                  '#tree' => TRUE,
                  '#theme' => 'table',
                  '#header' => $header,
                  'values' => $data_to_send,
                  '#rows' => &$rows,
                );
            }
            $form['add_email'] = array(
              '#type' => 'item',
              '#theme' => 'add_email',
              '#attributes' => array('class' => array('add-email')),
              '#weight' => -20,
              '#open' => TRUE,
            );

            $form['remove_email'] = array(
              '#type' => 'item',
              '#theme' => 'remove_email',
              '#attributes' => array('class' => array('remove-email')),
              '#weight' => -20,
              '#open' => TRUE,
            );
        }

        $form['account']['current_pass_required_value']['#access'] = FALSE;
        $form['account']['current_pass']['#access'] = FALSE;

        if ($config->get('ciam_enable_2fa') == 'true') {
            $form['lr_2fa_container'] = array(
              '#type' => 'item',
              '#theme' => '2fa_container',
              '#attributes' => array('class' => array('lr-2fa-container')),
              '#weight' => -25,
              '#open' => TRUE,
            );

            try {
                $isEnabled = $userObject->configureTwoFAByToken($_SESSION['access_token']);
            }
            catch (LoginRadiusException $e) {
                \Drupal::logger('ciam')->error($e);
            }

            if ((isset($isEnabled->IsGoogleAuthenticatorVerified) && $isEnabled->IsGoogleAuthenticatorVerified) || (isset($isEnabled->IsOTPAuthenticatorVerified) && $isEnabled->IsOTPAuthenticatorVerified)) {
                $form['lr_2fa_backup'] = array(
                  '#type' => 'details',
                  '#title' => 'Backup Codes List',
                  '#theme' => 'lr_backup_codes',
                  '#attributes' => array('class' => array('lr_2fa_backup')),
                  '#weight' => -21,
                  '#open' => TRUE,
                );
            }
        }

       if ($config->get('enable_linking') == '1' && ((isset($_SESSION['emailVerified']) && $_SESSION['emailVerified']) || ($config->get('ciam_login_type') == 'phone' && $config->get('ciam_enable_phone_login') == 'true'))) {
            $form['lr_ciam_linked'] = array(
              '#type' => 'details',
              '#title' => $config->get('linking_text') ? $config->get('linking_text') : 'Account Linking',
              '#theme' => 'lr_ciam_linked',
              '#attributes' => array('class' => array('lr-ciam-linked')),
              '#weight' => -20,
              '#open' => TRUE,
            );
        }
    }
    return $form;
}

/**
 * Unset validation for current password.
 *
 * @param $fields
 * @param $entity_type
 */
function lr_ciam_entity_base_field_info_alter(&$fields, EntityTypeInterface $entity_type) {
    if (\Drupal::moduleHandler()->moduleExists('lr_ciam')) {
        if ($entity_type->id() == 'user') {
            $constraints = $fields['mail']->getConstraints();
            unset($constraints['ProtectedUserField']);
            $fields['mail']->setConstraints($constraints);

            $constraints = $fields['pass']->getConstraints();
            unset($constraints['ProtectedUserField']);
            $fields['pass']->setConstraints($constraints);
        }
    }
}

/**
 * Delete user.
 *
 * @param $account
 */
function lr_ciam_user_predelete($account) {

    $user_manager = \Drupal::service('lr_ciam.user_manager');
    $ciam_uid = $user_manager->lr_ciam_get_ciam_uid($account->id());

    $result = $user_manager->user_delete($ciam_uid);
    $user_manager->deleteMapUser($account->id());
}

/**
 * Implement hook_mail_alter().
 *
 * @param $message
 * 
 */
function lr_ciam_mail_alter(&$message) {
    if ($message['key'] == 'register_admin_created') {
        $message['send'] = FALSE;
    }
    if ($message['key'] == 'password_reset') {
        $message['send'] = FALSE;
    }
}
/**
 * Unset options when hosted page enable.
 *
 * @return $form
 */
function lr_ciam_form_advanced_settings_alter(&$form, FormStateInterface $form_state){
  $hd_config = \Drupal::config('hostedpage.settings'); 
 
  if($hd_config->get('lr_hosted_page_enable') == '1'){
    unset($form['lr_user_settings']);
    unset($form['lr_login_settings']);
    unset($form['lr_phone_settings']);
    unset($form['lr_2fa_settings']);
  }
  return $form;
}

/**
 * Add variable in db.
 *
 */
function lr_ciam_add_extra_config_settings() {
    return array('ciam_inform_validation_messages', 'ciam_terms_and_condition_html',
      'ciam_form_render_delay', 'ciam_min_password_length', 'ciam_max_password_length','ciam_welcome_email_template',
      'ciam_forgot_password_template', 'ciam_email_verification_template', 'ciam_custom_options','ciam_auto_hide_messages',
      'ciam_login_type', 'ciam_email_verification_condition', 'ciam_enable_login_on_email_verification',
      'ciam_prompt_password_on_social_login', 'ciam_enable_user_name', 'ciam_ask_required_field_on_traditional_login',
      'ciam_ask_email_always_for_unverified', 'ciam_enable_remember_me', 'ciam_display_password_strength', 'ciam_debug_mode', 'ciam_instant_link_login','ciam_instant_link_login_email_template',
      'ciam_instant_link_login_button_label', 'ciam_enable_recaptcha', 'ciam_v2_recaptcha_type', 'ciam_v2_recaptcha_site_key', 'ciam_enable_phone_login', 'ciam_sms_template',
      'ciam_exist_phone_number', 'ciam_instant_otp_login','ciam_sms_template_one_time_passcode','ciam_instant_otp_login_button_label', 'ciam_sms_template_phone_verification', 'ciam_enable_2fa', 'ciam_2fa_flow', 'ciam_google_authentication', 'ciam_sms_template_2fa');
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Add Social Login interface on register page.
 * Prefill user profile data when force registration is off.
 *
 * @param $form
 * @param FormStateInterface $form_state
 */
function lr_ciam_form_user_register_form_alter(&$form, FormStateInterface $form_state) {
    $config = \Drupal::config('ciam.settings');

    if (isset($_SESSION['social_lrdata'])) {
        $userprofile = $_SESSION['social_lrdata'];
        unset($_SESSION['social_lrdata']);

        if (isset($userprofile->ID) && !empty($userprofile->ID)) {
            $user_manager = \Drupal::service('lr_ciam.user_manager');
            $data = $user_manager->checkExistUsername($userprofile);
            $form['account']['name']['#default_value'] = $data['username'];
            $form['account']['mail']['#default_value'] = '';

            if ($config->get('verify_mail') == 1) {
                $form['account']['pass']['#type'] = 'hidden';
                $form['account']['pass']['#value'] = user_password();
            }
            $user_manager->field_create_user_array($form, $userprofile);
        }
    }
}

/**
 * Validate LoginRadius API Credentials.
 *
 * @param $apikey
 * @param $apisecret
 * @return array
 */
function lr_ciam_get_authentication($apikey, $apisecret) {

    if (isset($apikey)) {
        $data = array();
        try {
            $socialLoginObject = new SocialLoginAPI($apikey, $apisecret, array('authentication' => false, 'output_format' => 'json'));
            $result = $socialLoginObject->validateKeyandSecret();

            if (empty($result)) {
                $data['message'] = t('please check your php.ini settings to enable CURL or FSOCKOPEN');
                $data['status'] = 'error';
            }
            elseif (isset($result->Status) && !$result->Status) {
                $error = array(
                  "API_KEY_NOT_VALID" => "LoginRadius API key is invalid. Get your LoginRadius API key from LoginRadius account",
                  "API_SECRET_NOT_VALID" => "LoginRadius API Secret is invalid. Get your LoginRadius API Secret from LoginRadius account",
                  "API_KEY_NOT_FORMATED" => "LoginRadius API Key is not formatted correctly",
                  "API_SECRET_NOT_FORMATED" => "LoginRadius API Secret is not formatted correctly",
                );

                foreach ($result->Messages as $value) {
                    $data['message'] = $error["$value"];
                    $data['status'] = 'error';
                    break;
                }
            }
            return $data;
        }
        
        catch (LoginRadiusException $e) {
            $data['message'] = "Something went wrong, check your credentials.";
            $data['status'] = 'error';
            return $data;
        }
    }
}

/**
 * Implements hook_user_delete().
 * 
 * @param $account
 *
 */
function lr_ciam_user_delete($account) {
    if (!\Drupal::moduleHandler()->moduleExists('lr_ciam')) {
        $user_manager = \Drupal::service('lr_ciam.user_manager');
        $user_manager->deleteMapUser($account->id());
    }
}
